### ISSUE TITLE
Quality Issue with DIGIT's

### ISSUE THREAD

**Issue by ejharber** [facebookresearch/digit-interface#15]
I was wondering if anyone else has seen a drop in quality of the Digit Gels? I ordered some DIGITS a while ago and the gel's that came with them were pristine. However I just ordered a new batch and there were quite a few defects which cause issues with some of our CV algorithms. If anyone else is experiencing the same issue I'd appreciate some support or maybe some better quality control in the future.  

[Digit Sensors (1).pdf](https://github.com/facebookresearch/digit-interface/files/13461345/Digit.Sensors.1.pdf)

**Comment by robertocalandra** [comment]
Hi @ejharber,
Unfortunately, we cannot help you, since we did not provide the elastomers that you are using. 
I assume that you ordered the elastomers from GelSight Inc.? If so, I should clarify that GelSight Inc. is an independent company, and we are not involved with their manufacturing process (although we transferred to them the manufacturing process that we developed). 
If you have concerns about the quality of the elastomer that they provide, my suggestion would be to get in touch directly with them.

PS: on a personal note, I also noticed that the manufacturing process that they currently use somehow lead to a quality of image inferior to the one that we had with hand-made elastomers. From visual inspection, this seems to be because of the coating layer which is less uniform, and more transparent.

**Comment by ejharber** [comment]
Thank you for your response @robertocalandra. Yes! we are currently purchasing our Elastomers from GelSight Inc. I sent them an email regarding this issue a few weeks ago and they actually directed me here. 

"We received a response from Meta, and they confirmed that the DIGIT gels you emailed about meet their specification and are acceptable.  There is a place to post issues on DIGIT at https://github.com/facebookresearch/digit-interface/issues.

Perhaps it would be helpful to post your findings directly there for some additional feedback."

Do you happen to know where else might be acceptable to post?

PS Thank you for your validation of my complaint, its good to know that others are having similar issues!
